import 'reflect-metadata';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import pg from 'pg';
import { NestFactory } from '@nestjs/core';
import { createRequire } from 'node:module';
const { JwtService } = createRequire(new URL('../apps/api/package.json', import.meta.url))('@nestjs/jwt');
import appModule from '../apps/api/dist/app.module.js';
import authModule from '../apps/api/dist/auth/auth.service.js';
const url=process.env.AUDIT_DATABASE_URL;
assert.ok(url && new URL(url).pathname.includes('audit'));
assert.equal(url,process.env.DATABASE_URL);
const api=process.env.AUDIT_API_URL ?? 'http://127.0.0.1:4400';
assert.ok(['127.0.0.1','localhost'].includes(new URL(api).hostname));
process.env.SUPERADMIN_EMAIL='final-qa-super@example.invalid';
process.env.SUPERADMIN_PASSWORD='FinalQaSuperSecret2026';
const db=new pg.Client({connectionString:url});await db.connect();
const app=await NestFactory.createApplicationContext(appModule.AppModule,{logger:['error','warn']});
const checks=[];const pass=name=>{checks.push(name);console.log(`PASS ${name}`)};
try {
 await app.get(authModule.AuthService).ensureConfiguredSuperadmin();
 async function req(path,body,token,method,headers={}) {
  const r=await fetch(api+path,{method:method??(body===undefined?'GET':'POST'),headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`} : {}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});
  return {status:r.status,value:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};
 }
 const superLogin=await req('/v1/auth/login',{email:process.env.SUPERADMIN_EMAIL,password:process.env.SUPERADMIN_PASSWORD,deviceId:randomUUID(),deviceName:'QA Superadmin'});
 assert.equal(superLogin.status,200);const superToken=superLogin.value.token;
 const suffix=randomUUID().slice(0,8);
 const created=await req('/v1/superadmin/stores',{storeName:`QA Auth ${suffix}`,ownerDisplayName:'QA Secondary Owner',ownerEmail:`owner-${suffix}@example.invalid`,ownerPassword:'QASecondarySecret2026'},superToken);
 assert.equal(created.status,201);const storeId=created.value.store.id;
 const credentials={email:`owner-${suffix}@example.invalid`,password:'QASecondarySecret2026',deviceId:randomUUID(),deviceName:'QA secondary device'};
 let ownerLogin=await req('/v1/auth/login',credentials);assert.equal(ownerLogin.status,428);
 assert.equal((await req(`/v1/auth/device-enrollments/${ownerLogin.value.challengeId}/decision`,{approve:true},superToken)).status,201);
 ownerLogin=await req('/v1/auth/login',credentials);assert.equal(ownerLogin.status,200);
 const token=ownerLogin.value.token;
 assert.equal((await req('/v1/superadmin/stores',undefined,token)).status,403);
 const originalStore=(await db.query("SELECT id FROM stores WHERE name LIKE 'Audit Store %' LIMIT 1")).rows[0].id;
 assert.equal((await req(`/v1/stores/${originalStore}/bootstrap`,undefined,token)).status,403);
 pass('superadmin creates store; manager enrollment; cross-store and superadmin scope enforced');
 const adminCred={email:`admin-${suffix}@example.invalid`,password:'QAAdminSecret2026',deviceId:credentials.deviceId,deviceName:'QA admin device'};
 const admin=await req(`/v1/stores/${storeId}/staff`,{role:'admin',displayName:'QA Admin',email:adminCred.email,password:adminCred.password},token);
 assert.equal(admin.status,201);
 const adminLogin=await req('/v1/auth/login',adminCred);assert.equal(adminLogin.status,200);
 assert.equal((await req(`/v1/stores/${storeId}/bootstrap`,undefined,adminLogin.value.token)).status,200);
 assert.equal((await req(`/v1/stores/${storeId}/staff`,undefined,adminLogin.value.token)).status,200);
 assert.equal((await req('/v1/superadmin/stores',undefined,adminLogin.value.token)).status,403);
 assert.equal((await req(`/v1/stores/${storeId}/staff/${admin.value.staff.id}/reset-secret`,{password:'QAAdminChanged2026'},token,'PATCH')).status,200);
 assert.equal((await req('/v1/auth/me',undefined,adminLogin.value.token)).status,401);
 pass('admin can manage its store, cannot use superadmin APIs, and password reset revokes its session');
 const cashier=await req(`/v1/stores/${storeId}/staff`,{role:'cashier',displayName:'QA Revocation Cashier',staffCode:`QA-${suffix}`,pin:'2468'},token);
 assert.equal(cashier.status,201);
 const cashierId=cashier.value.staff.id;assert.ok(cashierId);
 const cashierCred={storeId,staffCode:`QA-${suffix}`,pin:'2468',deviceId:credentials.deviceId,deviceName:'QA secondary device'};
 const cashierLogin=await req('/v1/auth/cashier-login',cashierCred);assert.equal(cashierLogin.status,200);
 assert.equal((await req(`/v1/stores/${storeId}/staff`,undefined,cashierLogin.value.token)).status,403);
 assert.equal((await req(`/v1/stores/${storeId}/staff/${cashierId}/reset-secret`,{pin:'8642'},token,'PATCH')).status,200);
 assert.equal((await req('/v1/auth/me',undefined,cashierLogin.value.token)).status,401);
 assert.equal((await req('/v1/auth/me',undefined,token)).status,200);
 const newCash=await req('/v1/auth/cashier-login',{...cashierCred,pin:'8642'});assert.equal(newCash.status,200);
 assert.equal((await req(`/v1/stores/${storeId}/staff/${cashierId}/disable`,{},token,'PATCH')).status,200);
 assert.equal((await req('/v1/auth/me',undefined,newCash.value.token)).status,401);
 pass('cashier forbidden from staff access; PIN reset and staff disable revoke existing tokens without revoking owner');
 const decoded=new JwtService().decode(token); delete decoded.exp; delete decoded.iat;
 const expired=new JwtService().sign(decoded,{secret:process.env.JWT_SECRET,expiresIn:-1});
 assert.equal((await req('/v1/auth/me',undefined,expired)).status,401);
 const refresh=await req('/v1/auth/refresh',{},undefined,undefined,{cookie:ownerLogin.cookie});assert.equal(refresh.status,200);
 assert.equal((await req('/v1/auth/refresh',{},undefined,undefined,{cookie:ownerLogin.cookie})).status,401);
 assert.equal((await req('/v1/auth/me',undefined,refresh.value.token)).status,200);
 pass('expired access token rejected; refresh rotates and old refresh cookie cannot replay');
 assert.equal((await req(`/v1/superadmin/stores/${storeId}/status`,{isActive:false},superToken,'PATCH')).status,200);
 assert.equal((await req('/v1/auth/me',undefined,refresh.value.token)).status,401);
 assert.equal((await req(`/v1/superadmin/stores/${storeId}/status`,{isActive:true},superToken,'PATCH')).status,200);
 ownerLogin=await req('/v1/auth/login',credentials);assert.equal(ownerLogin.status,200);
 assert.equal((await req(`/v1/superadmin/stores/${storeId}/staff/${created.value.staff.id}/reset-secret`,{password:'QAChangedOwnerSecret2026'},superToken,'PATCH')).status,200);
 assert.equal((await req('/v1/auth/me',undefined,ownerLogin.value.token)).status,401);
 ownerLogin=await req('/v1/auth/login',{...credentials,password:'QAChangedOwnerSecret2026'});assert.equal(ownerLogin.status,200);
 assert.equal((await req(`/v1/auth/devices/${credentials.deviceId}/revoke`,{},superToken)).status,201);
 assert.equal((await req('/v1/auth/me',undefined,ownerLogin.value.token)).status,401);
 pass('store suspension, owner password reset, and device revocation invalidate sessions');
 console.log(JSON.stringify({ok:true,checks}));
}finally{await app.close();await db.end();}
